-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "cnpj" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Local" ALTER COLUMN "cep" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Responsible" ALTER COLUMN "cep" SET DATA TYPE TEXT;
